# Generated by Django 3.1 on 2020-08-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(max_length=200, verbose_name='Pergunta')),
                ('alternativa1', models.CharField(max_length=200, verbose_name='Alternativa 1')),
                ('alternativa2', models.CharField(max_length=200, verbose_name='Alternativa 2')),
                ('alternativa3', models.CharField(max_length=200, verbose_name='Alternativa 3')),
                ('alternativa4', models.CharField(max_length=200, verbose_name='Alternativa 4')),
                ('alternativa5', models.CharField(max_length=200, verbose_name='Alternativa 5')),
                ('resposta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=5, verbose_name='Resposta')),
            ],
        ),
    ]
